### ISSUE TITLE
Prop Dependencies

### ISSUE THREAD

**Issue by aarondack** [kauffecup/react-bubble-chart#9]
Hey there!

I've been playing around with this bubble chart and noticed a discrepancy between the docs and what is actually happening. It lists some props as optional but in most cases they are required for the full functionality of the component. 

For instance,

```javascript
<ReactBubbleChart
   ....
   onClick={someFunc()}
   legend={false}
/>
```
Will result in that onClick handler never properly firing. Indeed it also appears that other props are dependent on this legend prop being set to true. I would expect onClick to happen _regardless_ of whether or not the optional legend prop has been supplied. 

Thoughts?

**Comment by danilotorrisi** [comment]
I found the issue, the problem is that when the legend is false, its svg.bubble-legend ( empty ) element is placed on top of the chart and it catches all the pointer events that won't reach div.bubble-label elements that actually have the onClick handler.

The workaround I found is to disable the pointer events on the bubble-lengend:
`.bubble-legend {
  pointer-events: none;
}`

**Comment by SaifurRahmanMohsin** [comment]
Why is onClick defined in the ReactBubbleChart rather than passed in as data? I'm curious because I would like to know in which bubble the click happened so that I can pass some data of that bubble to my click handler.
